### ISSUE TITLE
Could you please add support for 0.13.0-alpha

### ISSUE THREAD

**Issue by fabiopedrosa** [Surnet/docker-wkhtmltopdf#12]

**Comment by chdanielmueller** [comment]
Seems like they are still working on the building of the application. I don't think there is any benefit to work now on a build for 0.13-alpha on Alpine.

What's the use case you would like to use this version for?

**Comment by tonyellow** [comment]
I also need a newer version, 0.12.6 dev for example. The current master version 0.12.5 has some serious bugs, like TOC (table of contents) that is not being generated. This is fixed in 0.12.6 dev but the guy never officially released it beacuse he is to busy. The build can be found here (https://builds.wkhtmltopdf.org/0.12.6-dev/) but i have no clue how to include this into docker. It would be awesome if you could provide us with this newer versions with surnet.

**Comment by wade0817wang** [comment]
hi, @chdanielmueller   any plan to build a new version of wkhtmltopdf  0.12.6 release?

**Comment by chdanielmueller** [comment]
@wade0817wang I'll try building 0.12.6
If it works I will release it. But if not I can not do a lot of investigations.

From 0.12.7 there should be an official package available @wkhtmltopdf/packaging#2

**Comment by chdanielmueller** [comment]
Versions are released

**Comment by wade0817wang** [comment]
Great!  thanks
